### PR TITLE
Travis, add php7

### PR DESCRIPTION
**Pull request by gillesbourgeat**

### CODE REVIEW

**Comment by lunika** [comment]
Did you notice taht it's slower with php7 and HHVM :-D ?

**Comment by gillesbourgeat** [comment]
@lunika :+1: That's a good observation !

**Comment by bilhackmac** [comment]
It's not running with the same version of PHPUnit for PHP7, it's maybe for that

**Comment by bilhackmac** [comment]
Also, PHP7 need to be installed => https://travis-ci.org/thelia/math-tools/jobs/94819086#L86

**Comment by lunika** [comment]
Oh I was just talking about the phpunit execution, not the total time for travis execution.

**Comment by lunika** [comment]
it's not the same version of phpunit because the phpunit installed by composer is not used. But the blobal phpunit installed on travis. 
It would be great to fix that in fact.

**Pull request merged**
